#!/bin/bash
#
# libs/tools/generate_swagger_assets.sh
#
# Genere les headers C++ embeddes depuis les fichiers
# Swagger UI deja telecharges dans assets/swagger-ui/.
#
# Le script peut etre lance depuis n'importe ou.

set -e

# Determine la racine du repo automatiquement
# Ce script est dans libs/tools/, la racine est 2 niveaux au-dessus
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

ASSETS_DIR="$REPO_ROOT/assets/swagger-ui"
OUTPUT_DIR="$REPO_ROOT/apps/Backend_Seastar/src/http/swagger/generated"

echo "🔍 Repertoire racine du repo : $REPO_ROOT"
echo "🔍 Assets source              : $ASSETS_DIR"
echo "🔍 Output                     : $OUTPUT_DIR"
echo ""

# Verification : les fichiers source existent ?
if [ ! -d "$ASSETS_DIR" ]; then
    echo "❌ ERREUR : le dossier $ASSETS_DIR n'existe pas"
    echo "   Place les fichiers Swagger UI dans ce dossier d'abord."
    exit 1
fi

REQUIRED_FILES=(
    "swagger-ui.css"
    "swagger-ui-bundle.js"
    "swagger-ui-standalone-preset.js"
    "favicon-32x32.png"
)

for f in "${REQUIRED_FILES[@]}"; do
    if [ ! -f "$ASSETS_DIR/$f" ]; then
        echo "❌ ERREUR : fichier manquant : $ASSETS_DIR/$f"
        exit 1
    fi
done

echo "📂 Creation du dossier de sortie : $OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"

echo "📦 Generation des headers C++..."

# Helper pour generer un .h depuis un fichier
generate_header() {
    local input_file="$1"
    local var_name="$2"
    local output_file="$3"

    {
        echo "// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY"
        echo "// Generated by libs/tools/generate_swagger_assets.sh"
        echo "// Source: $(basename ${input_file})"
        echo ""
        echo "#pragma once"
        echo ""
        echo "#include <cstddef>"
        echo ""
        echo "namespace sea::http::swagger {"
        echo ""
        xxd -i -n "${var_name}" "${input_file}" \
            | sed 's/unsigned char/inline constexpr unsigned char/' \
            | sed 's/unsigned int/inline constexpr unsigned int/'
        echo ""
        echo "} // namespace sea::http::swagger"
    } > "${output_file}"

    echo "  ✓ $(basename ${output_file}) ($(stat -c%s "${output_file}") bytes)"
}

generate_header "$ASSETS_DIR/swagger-ui.css" \
                "swagger_ui_css_data" \
                "$OUTPUT_DIR/swagger_ui_css.h"

generate_header "$ASSETS_DIR/swagger-ui-bundle.js" \
                "swagger_ui_bundle_js_data" \
                "$OUTPUT_DIR/swagger_ui_bundle_js.h"

generate_header "$ASSETS_DIR/swagger-ui-standalone-preset.js" \
                "swagger_ui_standalone_preset_js_data" \
                "$OUTPUT_DIR/swagger_ui_standalone_preset_js.h"

generate_header "$ASSETS_DIR/favicon-32x32.png" \
                "swagger_favicon_data" \
                "$OUTPUT_DIR/swagger_favicon.h"

echo ""
echo "✅ Fichiers generes dans : $OUTPUT_DIR"
echo ""
echo "Contenu :"
ls -la "$OUTPUT_DIR"
